version: "3"

services:
    ubuntu:
        build:
            context: ubuntu
            args:
                - UBUNTU_VERSION=16.04
                - VNC_PASSWORD=${VNC_PASSWORD}
        image: ubuntu_vnce
        container_name: ubuntu_vnc1
        ports:
            - "5901:5901"
            # - ":"
